spring.application.name=todo-app

# Configuración directa para Railway
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

server.address=0.0.0.0
server.port=${PORT:9000}

# URL del API REST (hardcodeada)
todo.rest.url=https://todo-rest-production-0496.up.railway.app

