spring.application.name=todo-app

spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show_sql=true

todo.rest.url=https://todo-rest-production-0496.up.railway.app
server.address=0.0.0.0
server.port=${PORT:8080}
