spring.application.name=todo-app

#esto deshabilita la autoconfiguracion de la bbdd
spring.autoconfigure.exclude=\
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
    org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server.port=9000
#todo.rest.url=http://localhost:8080

# URL del API REST
todo.rest.url=${TODO_REST_URL:http://localhost:8080}